language: cpp
compiler:
  - g++
  - clang++
dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake

branches:
  only:
    - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
