language: cpp
compiler: g++

dist: trusty
sudo: require

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake

branches:
  only:
    - master

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
