dist: trusty
sudo: require
language: cpp
compiler: g++

before_install:
  - sudo apt-get update

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake

branches:
  only:
    - master

before_script:
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
